fix(ssl): disable SSL verification in alpine apk
this is workaround commit around this error:
```
Step 11/16 : RUN apk add --no-cache hwdata && rm -rf /var/cache/apk/*
 ---> Running in 0981effde6a0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
486BC8EB1B7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: Permission denied
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
486BC8EB1B7F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889:
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: Permission denied
ERROR: unable to select packages:
  hwdata (no such package):
    required by: world[hwdata]
The command '/bin/sh -c apk add --no-cach
```

Signed-off-by: Boris Glimcher <36732377+glimchb@users.noreply.github.com>